version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb-library
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  websvr:
    build: ./work
    container_name: web4mongo-library
    volumes:  
      - ./work/app:/var/www/html
    ports:
      - 8080:80
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: mongopwd
      MONGODB_DB: Biblioteca

  mongo-express:
    image: mongo-express:latest
    container_name: mongoex-library
    ports:
      - 8081:8081     
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongodb://root:mongopwd@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo