version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  websvr:
    build: ./work
    container_name: web4mongo
    volumes:  
      - ./work/app:/var/www/html
    ports:
      - 8080:80
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: pass
      MONGODB_DB: Biblioteca

  mongo-express:
    image: mongo-express
    container_name: mongoex
    ports:
      - 8081:8081     
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongodb://root:mongopwd@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo