version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb-library
    environment:
      MONGO_INITDB_ROOT_USERNAME: Bibliotecario_akashic
      MONGO_INITDB_ROOT_PASSWORD: userM4st3r_4temp_10282023

  websvr:
    build: ./work
    container_name: web4mongo-library
    volumes:  
      - ./work/app:/var/www/html
    ports:
      - 9090:80
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGODB_USERNAME: Bibliotecario_akashic
      MONGODB_PASSWORD: userM4st3r_4temp_10282023
      MONGODB_DB: Biblioteca

  mongo-express:
    image: mongo-express:latest
    container_name: mongoex-library
    ports:
      - 9091:8081     
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Bibliotecario_akashic
      ME_CONFIG_MONGODB_ADMINPASSWORD: userM4st3r_4temp_10282023
      ME_CONFIG_MONGODB_URL: mongodb://Bibliotecario_akashic:userM4st3r_4temp_10282023@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo